### PR TITLE
PANDARIA: update fluentd image

### PR DESCRIPTION
**Pull request by GGGitBoy**
update fluentd image 

**Relate issue:**
https://github.com/cnrancher/pandaria/issues/337

### CODE REVIEW

**Comment by GGGitBoy** [comment]
this PR need to update when we get the **cnrancher/fluentd** image

**Comment by gitlawr** [comment]
需要提交到一个新的chart版本。分两个commit，一个copy 0.2.2000到0.2.2001版本，一个带上改动

**Comment by GGGitBoy** [comment]
Update!

**Review by guangbochen — APPROVED** [review]
LGTM

**Pull request merged**
