### PR TITLE
PANDARIA: Modify alertmanager replicaCount

### PR DESCRIPTION
**Pull request by GGGitBoy**
**Related issue:**

https://github.com/cnrancher/pandaria/issues/435

### CODE REVIEW

**Comment by gitlawr** [comment]
Is it sufficient using 2 replicas for HA?

**Comment by GGGitBoy** [comment]
Updated

**Comment by gitlawr** [comment]
I'm asking for discussion and evidence, not requesting for changes.

I think 3 is a common pattern for alertmanager HA given the following usages:

1. alertmanager example: https://github.com/prometheus/alertmanager#high-availability
2. openshift: https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html#allocating-enough-persistent-volumes
3. kube-prometheus(which is moved from prometheus-operator project): https://github.com/coreos/kube-prometheus/blob/master/manifests/alertmanager-alertmanager.yaml

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
